# Generated by Django 5.0.1 on 2024-01-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, null=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('descripcion', models.CharField(max_length=250, null=True)),
                ('textoNoticia1', models.CharField(max_length=250, null=True)),
                ('textoNoticia2', models.CharField(blank=True, max_length=250, null=True)),
                ('imagenEncabezado', models.ImageField(blank=True, null=True, upload_to='images')),
                ('imagenPrincipal', models.ImageField(blank=True, null=True, upload_to='images')),
                ('imagenSecundaria', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'db_table': 'Noticia',
            },
        ),
    ]
