# Generated by Django 5.0.1 on 2024-01-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_noticia_textonoticia1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRegion', models.CharField(max_length=50, null=True)),
                ('nombreCompletoDelegado', models.CharField(max_length=100, null=True)),
                ('correoDelegado', models.CharField(max_length=150, null=True)),
                ('fotoDelegado', models.ImageField(blank=True, null=True, upload_to='images')),
                ('nombreCompletoCompetidor', models.CharField(max_length=100, null=True)),
                ('fotoCompetidor', models.ImageField(blank=True, null=True, upload_to='images')),
                ('nombreCompletoCompetidora', models.CharField(max_length=100, null=True)),
                ('fotoCompetidora', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'db_table': 'Regiones',
            },
        ),
    ]
