# Generated by Django 5.0.1 on 2024-01-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_regiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChileRegiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=100, null=True)),
                ('imagenRegion', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
