# Generated by Django 5.0.1 on 2024-01-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_chileregiones'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chileregiones',
            table='ChileRegiones',
        ),
    ]
