# Generated by Django 5.0.1 on 2024-01-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_chileregiones_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChileRegiones',
        ),
        migrations.AddField(
            model_name='regiones',
            name='imagenRegion',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
