# Generated by Django 5.0.1 on 2024-01-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_delete_chileregiones_regiones_imagenregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnVivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activar_en_vivo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'EnVivos',
            },
        ),
        migrations.AlterField(
            model_name='regiones',
            name='correoDelegado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
