# Generated by Django 5.0.1 on 2024-02-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_regiones_votos'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiones',
            name='ips_votantes',
            field=models.TextField(blank=True),
        ),
    ]
