# Generated by Django 5.0.1 on 2024-02-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_regiones_ips_votantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiones',
            name='ips_votantes',
        ),
    ]
