# Generated by Django 5.0.1 on 2024-02-05 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_regiones_ips_votantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('nombreRegion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.regiones')),
            ],
        ),
    ]
