# Generated by Django 5.0.1 on 2024-02-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_votaciones'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='votaciones',
            table='Votacion',
        ),
    ]
