# Generated by Django 5.0.1 on 2024-02-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_votaciones_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiones',
            name='nombreCompletoCompetidor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='regiones',
            name='nombreCompletoCompetidora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
