# Generated by Django 5.0.1 on 2024-02-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_regiones_nombrecompletocompetidor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiones',
            name='nombreCompletoCompetidor',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='regiones',
            name='nombreCompletoCompetidora',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
