# Generated by Django 5.0.2 on 2024-02-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_regiones_nombrecompletocompetidor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envivos',
            name='link_transmision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
