# Generated by Django 5.0.2 on 2024-02-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_envivos_link_transmision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pareja', models.CharField(max_length=100, null=True)),
                ('anno_campeon', models.CharField(max_length=5, null=True)),
                ('foto_campeones', models.ImageField(null=True, upload_to='images')),
            ],
            options={
                'db_table': 'Campeones',
            },
        ),
    ]
