# Generated by Django 5.0.2 on 2024-07-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_campeones'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueVotaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activar_votaciones', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Votaciones',
            },
        ),
    ]
