# Generated by Django 5.0.2 on 2024-08-09 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_comuna_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bailarina', models.CharField(max_length=100)),
                ('edad_bailarina', models.PositiveIntegerField()),
                ('fecha_nacimiento_bailarina', models.DateField()),
                ('rut_bailarina', models.CharField(max_length=12)),
                ('email_bailarina', models.EmailField(max_length=254)),
                ('telefono_bailarina', models.CharField(max_length=15)),
                ('nombre_bailarin', models.CharField(max_length=100)),
                ('edad_bailarin', models.PositiveIntegerField()),
                ('fecha_nacimiento_bailarin', models.DateField()),
                ('rut_bailarin', models.CharField(max_length=12)),
                ('email_bailarin', models.EmailField(max_length=254)),
                ('telefono_bailarin', models.CharField(max_length=15)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.region')),
            ],
        ),
    ]
