# Generated by Django 5.0.2 on 2024-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_inscripcion_comuna_alter_inscripcion_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='textoNoticia1',
            field=models.CharField(max_length=1250, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='textoNoticia2',
            field=models.CharField(blank=True, max_length=1450, null=True),
        ),
    ]
